[package]
name = "nodes"
version = "0.1.0"
edition = "2024"

[dependencies]
barretenberg-rs = "=5.0.0-nightly.20260522"
proptest = "1.11.0"
sha2 = "0.11.0"
nargo = { git = "https://github.com/noir-lang/noir.git", rev = "f1a4575adac59af0a86b036cf73ff5883d142a91" }
noir_artifact_cli = { git = "https://github.com/noir-lang/noir.git", rev = "f1a4575adac59af0a86b036cf73ff5883d142a91" }
noirc_artifacts = { git = "https://github.com/noir-lang/noir.git", rev = "f1a4575adac59af0a86b036cf73ff5883d142a91" }
bn254_blackbox_solver = { git = "https://github.com/noir-lang/noir.git", rev = "f1a4575adac59af0a86b036cf73ff5883d142a91" }
acir = { git = "https://github.com/noir-lang/noir.git", rev = "f1a4575adac59af0a86b036cf73ff5883d142a91" }
noirc_abi = { git = "https://github.com/noir-lang/noir.git", rev = "f1a4575adac59af0a86b036cf73ff5883d142a91" }
flate2 = "1.0.24"
borsh = { version = "1.8.0", features = ["derive"] }
borsh-derive = { version = "1.8.0" }
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
