[workspace]
members = ["crates/transfer_auth", "crates/compliance", "crates/core", "crates/delta_verify", "crates/zk_aggregation", "crates/compliance_keccak_nodes", "crates/compliance_secp256k1_deltas", "crates/rollup_aggregation", "crates/root_rollup_aggregation"]
